### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by firstnecron** [firstnecron/tt-tic-tac-toe#1]
**Start Screen**
- [ ] Start screen appears when the page loads
- [ ] Play Game button loads the Tic Tac Toe board and start the game
- [ ] (Extra) Player is prompted to enter their name

**Game Board**
- [ ] Game alternates between O and X
- [ ] Active player identified on the page (The O or X is highlighted, depending on whose turn it is)
- [ ] Empty squares are highlighted with player's symbol when moused over
- [ ] Cannot click on already occupied squares
- [ ] Occupied squares are identified with an X or O
- [ ] (Extra) Player's name appears on the board screen
- [ ] (Extra) Player vs. computer. One side of the game is programatically controlled

**Game Finish**
- [ ] Games ends if player has 3 symbols in a row, or the board is full
- [ ] Finish screen appears announcing winner (or tie)
- [ ] New game button starts a new game on am empty board
- [ ] (Extra) Player's name appears if they win

**Uses modular pattern**
- [ ] Uses the module pattern or a self-invoking function literal
- [ ] Program is stored in, at most, one global variable

**Comment by firstnecron** [comment]
**Game Finish** (Extra work)
- [ ] Play again (Old new game) button starts a new game on am empty board
- [ ] New game button starts the entire game over - displaying the player prompt
